### ISSUE TITLE
History doesn't save for symbols with /

### ISSUE THREAD

**Issue by saetto** [SoftFx/QuotesDownloader#2]
History doesn't save for symbols with /
![QuotesDownloder](https://user-images.githubusercontent.com/25159834/58940093-48989180-8781-11e9-959d-b84fc4a0433d.jpg)

**Comment by GurritoN** [comment]
/ - invalid symbol in Windows file names. With current naming system for QuotesDownloader it can't be fixed

**Comment by GurritoN** [comment]
Now we use %2f instead of /
